### ISSUE TITLE
[Security] Use subprocess

### ISSUE THREAD

**Issue by pdvyas** [nagkumar91/cmpe273_ta#1]
https://github.com/nagkumar91/cmpe273_ta/blob/master/csv_to_git.py#L66

If a student's name is "Pratik Vyas && rm -rf /" it'll run `rm -rf /`.

**Comment by nagkumar91** [comment]
Interesting!
This scripts runs on the assumption that we have "sanitized" inputs. You can fork this and help me sanitize the inputs!

**Comment by pdvyas** [comment]
Even if the inputs were sanitised, I'd still not use os.system.

**Comment by nagkumar91** [comment]
I came across subprocess now and I will use that for the next time! 
Thank you for the dev ops tip! Appreciate it. Feel free to submit a fix using subprocess.

**Comment by pdvyas** [comment]
Yup sure :)

On Wed, Feb 24, 2016 at 8:48 PM, Nagkumar Arkalgud <notifications@github.com
