### ISSUE TITLE
[Grading Script] Unit test suggestion

### ISSUE THREAD

**Issue by pdvyas** [nagkumar91/cmpe273_ta#3]
For the case where I had `['travel']['flight']['seat'] == change_person['travel']['flight']['seat']` but `['favorite_sport'] != change_person['favorite_sport']`, the script did not indicate that there was something wrong.

Really appreciate that you gave us test cases :+1: 
Would you consider using unittest standard library in future?

sample (rewrote for assignment1), https://gist.github.com/pdvyas/185a23967c9b075908bd

**Comment by nagkumar91** [comment]
Will do!

**Comment by pdvyas** [comment]
Thanks!
